### ISSUE TITLE
Doesn't work on inactive tabs

### ISSUE THREAD

**Issue by morgoth** [adamcik/media-progress-timer#1]
I noticed this on latest Chrome (41.0.2272.101).
When the tab is inactive for some time, it stops working as probably `setTimeout` is not fired.
I didn't find any solution yet.
You can test it on http://mopster.cowbell-labs.com where this library is integrated.

**Comment by adamcik** [comment]
Didn't get a chance to verify this yesterday. Have you tried setting `disableRequestAnimationFrame` to true? Thing is that when using animation frames the browser won't actually create any frames unless the tab is active, and then catch it all up when you switch to it.

And a quick hint, looks you are setting the target update rate to 1000ms, this won't give you very smooth animations. You might want to try setting to 16ms ~60fps, 33ms ~30fps or 66ms ~15fps and see what you prefer. Of course this is all a trade off against how often you want to repaint and battery use etc :-)

**Comment by morgoth** [comment]
Looks like it's working with this option.
When I first saw it, I thought that this has something to do with legacy browsers ;-).
I'll try to understand what this option really does in free time.
Do you think it could be enabled by default in this library or at least has better description that it deals with this issue?

**Comment by adamcik** [comment]
Take a look at for instance http://www.paulirish.com/2011/requestanimationframe-for-smart-animating/ 
for more info on `requestAnimationFrame` and why it is usually preferable to timeout based animations. IMO the `requestAnimationFrame` variant that doesn't update when the frame isn't visible is a feature, not a bug.

As for the the option, it is basically just for me to test that the fallback mode works, and as an escape hatch if someone really wants the old behavior for some reason.

I've tested a bit with http://adamcik.github.io/media-progress-timer/ setting a longer duration and an update rate of 1000ms and can't seem to reproduce. In my test it will update as soon as the tab is active again.

**Comment by morgoth** [comment]
Thanks.
I'm using it to track progress of song played on Mopidy and in this case it's out of sync when animation is resumed.
